// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class GPGSIds
{
        public const string achievement_you_are_still_a_newbie = "CgkIqJW9u8saEAIQBA"; // <GPGSID>
        public const string achievement_youve_gone_too_far = "CgkIqJW9u8saEAIQBg"; // <GPGSID>
        public const string leaderboard_leaderboard = "CgkIqJW9u8saEAIQEA"; // <GPGSID>
        public const string achievement_hacker = "CgkIqJW9u8saEAIQCA"; // <GPGSID>
        public const string achievement_what_did_he_do_to_deserve_this = "CgkIqJW9u8saEAIQDA"; // <GPGSID>
        public const string achievement_nice_try = "CgkIqJW9u8saEAIQAg"; // <GPGSID>
        public const string achievement_yeah_boy = "CgkIqJW9u8saEAIQBQ"; // <GPGSID>
        public const string achievement_there_is_a_first_time_for_everything = "CgkIqJW9u8saEAIQAQ"; // <GPGSID>
        public const string achievement_poor_worm = "CgkIqJW9u8saEAIQCw"; // <GPGSID>
        public const string achievement_come_on_keep_going = "CgkIqJW9u8saEAIQCg"; // <GPGSID>
        public const string achievement_master_of_the_game = "CgkIqJW9u8saEAIQBw"; // <GPGSID>
        public const string achievement_dont_give_up = "CgkIqJW9u8saEAIQCQ"; // <GPGSID>
        public const string achievement_there_once_was_a_worm = "CgkIqJW9u8saEAIQDQ"; // <GPGSID>

}

